### ISSUE TITLE
Adding docs/best practices?

### ISSUE THREAD

**Issue by betatim** [appuio/charts#15]
Hi 👋 !

I was wondering what your plans are with respect to maintaining the charts in this repository. I'd like to deploy (for example) KeyCloak on openshift (and then appuio) via helm.

For example just `helm install stable/keycloak` isn't enough to get it to run (needs some securityContext stuff) which is straight forward once you know it. I assume other charts will be a bit like that, so should we add small snippets of READMEs in this repo for "these are some Stolpersteine and how to avoid them when using this chart on appuio"?

**Comment by ccremer** [comment]
Hi Tim
Sorry for the late response, we completely forgot about that.
Currently, @janPhil is occupied with making the keycloak chart openshift compatible. It should be a matter of days until we can provide a working keycloak chart for GA.
Other than that, most charts in this repo should be openshift compatible, otherwise we would use the upstream charts. As you said, some are just missing some openshift/security specifics.

**Comment by betatim** [comment]
We have been using the KC chart from https://github.com/helm/charts without having to modify it for a few weeks now. Seems fine.

Getting things upstreamed in that repo also worked well (in terms of developer experience) when we wanted to make the security context configurable for the logstash chart.

**Comment by ccremer** [comment]
Hi Tim
Do you have further questions? Can this issue be closed?
